name: lint
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  elvis:
    runs-on: ubuntu-latest
    container:
      image: erlang:27
    steps:
      - uses: actions/checkout@v4
      - run: rebar3 as lint lint
